version: 0.0.{build}

# Test against the latest version of this Node.js version
image:
  Visual Studio 2017
environment:
  nodejs_version: "11"
  PFX_KEY:
    secure: 301vAt8c2+69YqMuoyjG4wILdUkMkDkvkrpQblrC5DI=

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

after_test:
  - ps: |
      wget "https://nodejs.org/dist/v11.6.0/node-v11.6.0-win-x64.zip" -OutFile node.zip
      7z x node.zip
      rm node.zip
      mv node-v11.6.0-win-x64 node
      $env:Path = "$pwd\node;$env:Path";
      .\node\npm install --no-optional
      $env:TEST_ENV = 'ci'
      .\node\npm run test
      # bash scripts/testRun.sh
      set version "$env:APPVEYOR_REPO_TAG_NAME"
      if ([string]::IsNullOrEmpty("$version")) { set version "$env:APPVEYOR_REPO_COMMIT".Substring(0, 8) }
      mkdir dist
      .\buildtools\iscc "$pwd\metadata\exokit.iss" "/dMyAppVersion=$version" /odist /qp
      mv dist\*.exe exokit-win-x64.exe
      SignTool /f .\metadata\codesign-windows.pfx /p "$env:PFX_KEY" exokit-win-x64.exe

artifacts:
  - path: "exokit-win-x64.exe"
    name: exokit-windows-installer

deploy:
  - provider: GitHub
    description: 'Exokit installer'
    auth_token:
      secure: ewZJqEOOh1B8ZWAJyd2dikQZ9BtcN4Cv04WEirXNDT8m9J06ZHgsw8hVcYmTinw8
    artifact: "exokit-win-x64.exe"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: 45CGZx1wukHisNzZTeLLrdh/drSuJqO3uRJ7nxgon5RBePIM0QLR7lUKX16kPgzb9wAYgGt7A9E+ph8V9eFg+vkPoBZaIiV6GaS0PG3Xa1o=
    channel: '#builds'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/exokitxr/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/exokitxr/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

# Don't actually build.
build: off
