version: 0.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9.5.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # - npm test

after_test:
  - ps: |
      npm install --no-package-lock
      7z a windows-release.zip * -xr'!.git'

artifacts:
  - path: "windows-release.zip"
    name: windows-release

# Don't actually build.
build: off
